### PR TITLE
API change proposal

### PR DESCRIPTION
**Pull request by Rigo-m**
By leveraging useState and v-models I think we can make nuxt-modal have a better DX.

Not only is it easier to handle multiple modals in one component, but also you can easily access a modal status from within different parts of a project, just by using the same key.

Also, I've added the possibility to pass a v-model to an inline nuxt modal and forget about the name of the modal altogether, making some kind of "anonymous" modals.

Check App.vue to see the difference between the two implementations.

As a side note, this approach doesn't rely on reduntant close events as before

### CODE REVIEW

**Comment by Rigo-m** [comment]
I removed custom data content passed to the modal since I didn't see a clear usage of it.
It's also possible to pass the open/close method to slots for easier close implementation in buttons


Let me know what you think

**Comment by timb-103** [comment]
Great work, makes it much easier to use + the transitions are better on closing as we're not destroying the component when it closes.

Merged into master!

**Comment by timb-103** [comment]
PS. I updated the readme, let me know if you think it's good!

**Comment by Rigo-m** [comment]
LGTM :)

**Pull request merged**
